services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: cinefiles_db
      POSTGRES_USER: cinefiles_user
      POSTGRES_PASSWORD: cinefilespass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cinefiles_user -d cinefiles_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DEBUG=True
      - DB_NAME=cinefiles_db
      - DB_USER=cinefiles_user
      - DB_PASSWORD=cinefilespass
      - DB_HOST=db
      - DB_PORT=5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: cinefiles@admin.com  # Replace with your email
      PGADMIN_DEFAULT_PASSWORD: cinefilespass  # Replace with your password
    ports:
      - "5050:80"  # Expose pgAdmin on localhost:5050
    depends_on:
      - db

volumes:
  postgres_data: